Initial custom init package for Nutanix CSI driver
defenseunicorns/uds-bundle-software-factory-nutanix pull request #42
Opened 2024-03-20 00:31 UTC by jacobbmay

2024-05-01 14:23 UTC, blancharda requested changes
A few nits -- otherwise the changes look good!

One outstanding item is making sure we have the pepr policy exceptions in place. Let's update with main and update the [existing rook-ceph exception](https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/blob/main/packages/additional-manifests/pepr-policy-exemptions/rook-ceph-exemptions.yaml) accordingly (I would hazard a guess that this driver requires all the same permissions..)

2024-05-03 14:02 UTC, jacobbmay commented on config/uds-config.yaml
> -    JIRA_RWO_STORAGE_CLASS: "ceph-block"
I removed in favor of letting the the default storage class be used so it matches how every other package gets SC selected if they don't need RWX.

Makes it less of a hassle if the storage provider ever gets changed again for things that are using RWO block storage since we always make that the default.

2024-05-03 14:02 UTC, jacobbmay commented on config/uds-config.yaml
> -    CONFLUENCE_RWO_STORAGE_CLASS: "ceph-block"
Same as other comment

2024-05-03 14:06 UTC, jacobbmay commented on packages/init/values/namespaces.yaml
> +  - name: ntnx-system
That is just the default namespace used by the nutanix helm chart examples. I can update it but I don't think it is the only place they abbreviate nutanix to ntnx.

2024-05-03 14:15 UTC, jacobbmay commented on tasks.yaml
> +      - cmd: rm -f ./build/*
This could probably go back. When Anthony removed the uds tasks for deploying since the TUI doesn't work when deploying through tasks, he said he had just been putting his uds configs in a subdir of the build repo and running the deploy commands from that repo. I started doing the same and at some point ran a uds clean task without realizing it used the recursive flag and it deleted my configs. lol.

But this can be reverted and I can start putting them somewhere else like /scratch. lol

2024-05-03 16:01 UTC, blancharda commented on packages/init/values/namespaces.yaml
> +  - name: ntnx-system
If that's the default used elsewhere I'm cool with it

2024-05-03 17:31 UTC, blancharda commented on tasks.yaml
> +      - cmd: rm -f ./build/*
```suggestion
      - cmd: rm -f ./build/*
      + cmd: rm -rf ./build/*
```

2024-05-10 15:41 UTC, blancharda submitted a review, later dismissed

2024-05-10 16:00 UTC, anthonywendt approved these changes

2024-05-10 17:33 UTC, anthonywendt commented on packages/init/zarf.yaml
> +        url: https://github.com/jacobbmay/nutanix-helm.git # fork containing fix for imagepullsecrets needed for pods to pull images from zarf registry
I approved this, but I'm guessing we want to wait on merging until this is moved out of your personal repo?

2024-05-13 15:32 UTC, anthonywendt commented on packages/init/zarf.yaml
> +  # Push rook/ceph (and registry) images to permanent registry
```suggestion
  # Push nutanix csi (and registry) images to permanent registry
```

2024-05-13 15:33 UTC, anthonywendt commented on packages/init/zarf.yaml
> +    description: Push rook ceph images to the zarf registry
```suggestion
    description: Push nutanix csi images to the zarf registry
```

2024-05-13 16:00 UTC, anthonywendt approved these changes

2024-05-13 16:45 UTC, merged