chore: update uds-core to 0.17.0
defenseunicorns/uds-bundle-software-factory-nutanix pull request #77
Opened 2024-03-29 17:34 UTC by anthonywendt

chore: update gitlab to 16.9.2-uds.4
chore: update gitlab-runner to 16.10.0-uds.0
chore: update sonarqube to 8.0.3-uds.6
chore: update jira to 1.17.0-uds.2
chore: update confluence to 1.18.0-uds.0
chore: update mattermost to 9.4.1-uds.3

2024-03-29 23:43 UTC, blancharda requested changes
Updates for days!

Let's make sure to take a pass through the `docs/packages-and-dependencies` file before we merge.

2024-04-03 15:36 UTC, blancharda commented on config/test-cluster/uds-config.yaml
Since we are now storing the actual deploy configs elsewhere, we should consolidate this down to a single `example-config` folder so that we don't have to duplicate all changes.

2024-04-03 15:40 UTC, blancharda approved these changes
Looks good to me 👍

2024-04-03 19:04 UTC, blancharda requested changes
Couple of minor suggestions, otherwise, looks good!

2024-04-03 19:04 UTC, blancharda commented on bundles/uds-core-swf/uds-bundle.yaml
>          uds-mattermost-config:
Let's remove the defaults from the obj store endpoints as well since it is set in the config

2024-04-03 19:07 UTC, anthonywendt commented on bundles/uds-core-swf/uds-bundle.yaml
> +              path: insecureAdminPasswordGeneration.enabled
Not sure on this one. Was going to inherit the suggested default of false but expose it for configuration?

2024-04-03 19:19 UTC, blancharda commented on bundles/uds-core-swf/uds-bundle.yaml
> +              path: insecureAdminPasswordGeneration.enabled
I don't have particularly strong feelings about it, but I suspect it's going to end up in all of our configs either way lol

2024-04-03 21:45 UTC, blancharda approved these changes
lgtm

2024-04-05 15:52 UTC, merged